
# parsetab_g1.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'C D I L M V XromanNumber : thousand hundred ten digitthousand : M M M\n                | M M\n                | M\n                | lambdalow_hundreds : low_hundreds Clow_hundreds : lambdasmall_hundred : C C C\n                      | C C\n                      | Chundred : low_hundreds\n               | C M\n               | C D\n               | D low_hundreds\n               | lambdalow_tens : low_tens Xlow_tens : lambdasmall_ten : X X X\n                 | X X\n                 | Xten : low_tens\n           | X C\n           | X L\n           | L low_tens\n           | lambdalow_units : low_units Ilow_units : lambdasmall_digit : I I I\n                   | I I\n                   | Idigit : low_units\n             | I X\n             | I V\n             | V low_units\n             | lambdalambda :roman : romanNumber'
    
_lr_action_items = {'M':([0,3,7,10,],[3,10,17,21,]),'C':([0,2,3,4,6,8,9,10,13,16,19,20,21,],[-36,7,-4,-5,16,-36,-7,-3,28,-6,16,-7,-2,]),'D':([0,2,3,4,7,10,21,],[-36,8,-4,-5,18,-3,-2,]),'X':([0,2,3,4,5,6,8,9,10,12,14,15,16,17,18,19,20,21,24,27,30,31,],[-36,-36,-4,-5,13,-11,-36,-7,-3,27,-36,-17,-6,-12,-13,-14,-7,-2,33,-16,27,-17,]),'L':([0,2,3,4,5,6,8,9,10,13,16,17,18,19,20,21,],[-36,-36,-4,-5,14,-11,-36,-7,-3,29,-6,-12,-13,-14,-7,-2,]),'I':([0,2,3,4,5,6,8,9,10,11,12,14,15,16,17,18,19,20,21,23,25,26,27,28,29,30,31,32,35,36,],[-36,-36,-4,-5,-36,-11,-36,-7,-3,24,-21,-36,-17,-6,-12,-13,-14,-7,-2,32,-36,-27,-16,-22,-23,-24,-17,-26,32,-27,]),'V':([0,2,3,4,5,6,8,9,10,11,12,14,15,16,17,18,19,20,21,24,27,28,29,30,31,],[-36,-36,-4,-5,-36,-11,-36,-7,-3,25,-21,-36,-17,-6,-12,-13,-14,-7,-2,34,-16,-22,-23,-24,-17,]),'$end':([0,1,2,3,4,5,6,8,9,10,11,12,14,15,16,17,18,19,20,21,22,23,25,26,27,28,29,30,31,32,33,34,35,36,],[-36,0,-36,-4,-5,-36,-11,-36,-7,-3,-36,-21,-36,-17,-6,-12,-13,-14,-7,-2,-1,-31,-36,-27,-16,-22,-23,-24,-17,-26,-32,-33,-34,-27,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'romanNumber':([0,],[1,]),'thousand':([0,],[2,]),'lambda':([0,2,5,8,11,14,25,],[4,9,15,20,26,31,36,]),'hundred':([2,],[5,]),'low_hundreds':([2,8,],[6,19,]),'ten':([5,],[11,]),'low_tens':([5,14,],[12,30,]),'digit':([11,],[22,]),'low_units':([11,25,],[23,35,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> romanNumber","S'",1,None,None,None),
  ('romanNumber -> thousand hundred ten digit','romanNumber',4,'p_romanNumber','roman_parser1.py',11),
  ('thousand -> M M M','thousand',3,'p_thousand','roman_parser1.py',21),
  ('thousand -> M M','thousand',2,'p_thousand','roman_parser1.py',22),
  ('thousand -> M','thousand',1,'p_thousand','roman_parser1.py',23),
  ('thousand -> lambda','thousand',1,'p_thousand','roman_parser1.py',24),
  ('low_hundreds -> low_hundreds C','low_hundreds',2,'p_low_hundreds_rec','roman_parser1.py',40),
  ('low_hundreds -> lambda','low_hundreds',1,'p_low_hundreds_empty','roman_parser1.py',53),
  ('small_hundred -> C C C','small_hundred',3,'p_small_hundred','roman_parser1.py',58),
  ('small_hundred -> C C','small_hundred',2,'p_small_hundred','roman_parser1.py',59),
  ('small_hundred -> C','small_hundred',1,'p_small_hundred','roman_parser1.py',60),
  ('hundred -> low_hundreds','hundred',1,'p_hundred','roman_parser1.py',71),
  ('hundred -> C M','hundred',2,'p_hundred','roman_parser1.py',72),
  ('hundred -> C D','hundred',2,'p_hundred','roman_parser1.py',73),
  ('hundred -> D low_hundreds','hundred',2,'p_hundred','roman_parser1.py',74),
  ('hundred -> lambda','hundred',1,'p_hundred','roman_parser1.py',75),
  ('low_tens -> low_tens X','low_tens',2,'p_low_tens_rec','roman_parser1.py',91),
  ('low_tens -> lambda','low_tens',1,'p_low_tens_empty','roman_parser1.py',104),
  ('small_ten -> X X X','small_ten',3,'p_small_ten','roman_parser1.py',109),
  ('small_ten -> X X','small_ten',2,'p_small_ten','roman_parser1.py',110),
  ('small_ten -> X','small_ten',1,'p_small_ten','roman_parser1.py',111),
  ('ten -> low_tens','ten',1,'p_ten','roman_parser1.py',121),
  ('ten -> X C','ten',2,'p_ten','roman_parser1.py',122),
  ('ten -> X L','ten',2,'p_ten','roman_parser1.py',123),
  ('ten -> L low_tens','ten',2,'p_ten','roman_parser1.py',124),
  ('ten -> lambda','ten',1,'p_ten','roman_parser1.py',125),
  ('low_units -> low_units I','low_units',2,'p_low_units_rec','roman_parser1.py',140),
  ('low_units -> lambda','low_units',1,'p_low_units_empty','roman_parser1.py',153),
  ('small_digit -> I I I','small_digit',3,'p_small_digit','roman_parser1.py',158),
  ('small_digit -> I I','small_digit',2,'p_small_digit','roman_parser1.py',159),
  ('small_digit -> I','small_digit',1,'p_small_digit','roman_parser1.py',160),
  ('digit -> low_units','digit',1,'p_digit','roman_parser1.py',170),
  ('digit -> I X','digit',2,'p_digit','roman_parser1.py',171),
  ('digit -> I V','digit',2,'p_digit','roman_parser1.py',172),
  ('digit -> V low_units','digit',2,'p_digit','roman_parser1.py',173),
  ('digit -> lambda','digit',1,'p_digit','roman_parser1.py',174),
  ('lambda -> <empty>','lambda',0,'p_empty','roman_parser1.py',189),
  ('roman -> romanNumber','roman',1,'p_roman','roman_parser1.py',194),
]
