
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'C D I L M V XromanNumber : thousand hundred ten digitthousand : M M M\n                | M M\n                | M\n                | lambdalow_hundreds : C low_hundredslow_hundreds : lambdasmall_hundred : C C C\n                      | C C\n                      | Chundred : low_hundreds\n               | C M\n               | C D\n               | D low_hundreds\n               | lambdalow_tens : X low_tenslow_tens : lambdasmall_ten : X X X\n                 | X X\n                 | Xten : low_tens\n           | X C\n           | X L\n           | L low_tens\n           | lambdalow_units : I low_unitslow_units : lambdasmall_digit : I I I\n                   | I I\n                   | Idigit : low_units\n             | I X\n             | I V\n             | V low_units\n             | lambdalambda :roman : romanNumber'
    
_lr_action_items = {'M':([0,3,7,10,],[3,10,17,22,]),'C':([0,2,3,4,7,8,10,13,16,22,],[-36,7,-4,-5,16,16,-3,29,16,-2,]),'D':([0,2,3,4,7,10,22,],[-36,8,-4,-5,18,-3,-2,]),'X':([0,2,3,4,5,6,7,8,9,10,13,14,16,17,18,19,20,21,22,25,28,],[-36,-36,-4,-5,13,-11,-36,-36,-7,-3,28,28,-36,-12,-13,-6,-7,-14,-2,35,28,]),'L':([0,2,3,4,5,6,7,8,9,10,13,16,17,18,19,20,21,22,],[-36,-36,-4,-5,14,-11,-36,-36,-7,-3,30,-36,-12,-13,-6,-7,-14,-2,]),'I':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,25,26,28,29,30,31,32,33,34,],[-36,-36,-4,-5,-36,-11,-36,-36,-7,-3,25,-21,-36,-36,-17,-36,-12,-13,-6,-7,-14,-2,34,34,-36,-22,-23,-16,-17,-24,34,]),'V':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,25,28,29,30,31,32,33,],[-36,-36,-4,-5,-36,-11,-36,-36,-7,-3,26,-21,-36,-36,-17,-36,-12,-13,-6,-7,-14,-2,36,-36,-22,-23,-16,-17,-24,]),'$end':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,],[-36,0,-36,-4,-5,-36,-11,-36,-36,-7,-3,-36,-21,-36,-36,-17,-36,-12,-13,-6,-7,-14,-2,-1,-31,-36,-36,-27,-36,-22,-23,-16,-17,-24,-36,-32,-33,-26,-27,-34,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'romanNumber':([0,],[1,]),'thousand':([0,],[2,]),'lambda':([0,2,5,7,8,11,13,14,16,25,26,28,34,],[4,9,15,20,20,27,32,32,20,38,38,32,38,]),'hundred':([2,],[5,]),'low_hundreds':([2,7,8,16,],[6,19,21,19,]),'ten':([5,],[11,]),'low_tens':([5,13,14,28,],[12,31,33,31,]),'digit':([11,],[23,]),'low_units':([11,25,26,34,],[24,37,39,37,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> romanNumber","S'",1,None,None,None),
  ('romanNumber -> thousand hundred ten digit','romanNumber',4,'p_romanNumber','roman_parser2.py',10),
  ('thousand -> M M M','thousand',3,'p_thousand','roman_parser2.py',20),
  ('thousand -> M M','thousand',2,'p_thousand','roman_parser2.py',21),
  ('thousand -> M','thousand',1,'p_thousand','roman_parser2.py',22),
  ('thousand -> lambda','thousand',1,'p_thousand','roman_parser2.py',23),
  ('low_hundreds -> C low_hundreds','low_hundreds',2,'p_low_hundreds_rec','roman_parser2.py',39),
  ('low_hundreds -> lambda','low_hundreds',1,'p_low_hundreds_empty','roman_parser2.py',52),
  ('small_hundred -> C C C','small_hundred',3,'p_small_hundred','roman_parser2.py',57),
  ('small_hundred -> C C','small_hundred',2,'p_small_hundred','roman_parser2.py',58),
  ('small_hundred -> C','small_hundred',1,'p_small_hundred','roman_parser2.py',59),
  ('hundred -> low_hundreds','hundred',1,'p_hundred','roman_parser2.py',69),
  ('hundred -> C M','hundred',2,'p_hundred','roman_parser2.py',70),
  ('hundred -> C D','hundred',2,'p_hundred','roman_parser2.py',71),
  ('hundred -> D low_hundreds','hundred',2,'p_hundred','roman_parser2.py',72),
  ('hundred -> lambda','hundred',1,'p_hundred','roman_parser2.py',73),
  ('low_tens -> X low_tens','low_tens',2,'p_low_tens_rec','roman_parser2.py',88),
  ('low_tens -> lambda','low_tens',1,'p_low_tens_empty','roman_parser2.py',101),
  ('small_ten -> X X X','small_ten',3,'p_small_ten','roman_parser2.py',106),
  ('small_ten -> X X','small_ten',2,'p_small_ten','roman_parser2.py',107),
  ('small_ten -> X','small_ten',1,'p_small_ten','roman_parser2.py',108),
  ('ten -> low_tens','ten',1,'p_ten','roman_parser2.py',118),
  ('ten -> X C','ten',2,'p_ten','roman_parser2.py',119),
  ('ten -> X L','ten',2,'p_ten','roman_parser2.py',120),
  ('ten -> L low_tens','ten',2,'p_ten','roman_parser2.py',121),
  ('ten -> lambda','ten',1,'p_ten','roman_parser2.py',122),
  ('low_units -> I low_units','low_units',2,'p_low_units_rec','roman_parser2.py',137),
  ('low_units -> lambda','low_units',1,'p_low_units_empty','roman_parser2.py',150),
  ('small_digit -> I I I','small_digit',3,'p_small_digit','roman_parser2.py',155),
  ('small_digit -> I I','small_digit',2,'p_small_digit','roman_parser2.py',156),
  ('small_digit -> I','small_digit',1,'p_small_digit','roman_parser2.py',157),
  ('digit -> low_units','digit',1,'p_digit','roman_parser2.py',167),
  ('digit -> I X','digit',2,'p_digit','roman_parser2.py',168),
  ('digit -> I V','digit',2,'p_digit','roman_parser2.py',169),
  ('digit -> V low_units','digit',2,'p_digit','roman_parser2.py',170),
  ('digit -> lambda','digit',1,'p_digit','roman_parser2.py',171),
  ('lambda -> <empty>','lambda',0,'p_empty','roman_parser2.py',186),
  ('roman -> romanNumber','roman',1,'p_roman','roman_parser2.py',191),
]
